### ISSUE TITLE
recursive clone fails for users with only https access to github

### ISSUE THREAD

**Issue by eehouse** [5cript/bluez-rfcomm-example#3]
If I try to check out the project from a machine that doesn't authenticate me to github the recursive clones fail. That's because they're hard-coded to use a git: url. There doesn't seem to be any way to force git to use https for the recursive pulls, but there is a way you can structure the parent repo IFF all submodules can be expressed relatively.

https://stackoverflow.com/questions/40841882/automatically-access-git-submodules-via-ssh-or-https

**Comment by 5cript** [comment]
I never liked submodules much, too clunky, but also easier for others to use the repo.
I will fix that when I have the time.

**Comment by 5cript** [comment]
I have opted to plainly go for https links for now to keep it simple.
